<?php

use DebugBar\StandardDebugBar;

$debugbar = new StandardDebugBar();
$debugbarRenderer = $debugbar->getJavascriptRenderer();

?>

<style>
    body {
        margin: 0;
        padding: 0;
    }

    a:link,
    a:visited {
        color: #0398ca;
    }

    span#zf-name {
        color: #91be3f;
    }

    div#welcome {
        color: #fff;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        /*width:  100%;*/
        /*height: 400px;*/
        border: 2px solid #444;
        /*overflow: hidden;*/
        text-align: center;
    }

    div#more-information {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>

<style>
    <?php echo $debugbarRenderer->dumpCssAssets(); ?>
</style>

<!-- Manually import font-awesome 'cause debugBar is too dumb to have a proper path to the fonts -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>

<script>
    <?php echo $debugbarRenderer->dumpJsAssets(); ?>
</script>

<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>
    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p>
            <img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" />
        </p>

        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>

<?php echo $debugbarRenderer->render(); ?>
